FROM docker.io/jenkins/inbound-agent:latest-rhel-ubi9-jdk21

ENV CONTAINER_HOST=unix://run/podman/podman.sock
ARG PODMAN_REMOTE_ARCHIVE

USER root

ARG SELF_SIGNED_CERT_URL
ADD ${SELF_SIGNED_CERT_URL} /etc/pki/ca-trust/source/anchors/RelativIT.crt

RUN update-ca-trust && \
    dnf install -y jq gpg && \
    dnf clean all && \
    rm -rf /var/cache/dnf

COPY ${PODMAN_REMOTE_ARCHIVE} ${PODMAN_REMOTE_ARCHIVE}

RUN tar -xf ${PODMAN_REMOTE_ARCHIVE} --directory / && \
    mv /$(tar -tf ${PODMAN_REMOTE_ARCHIVE}) /bin/podman && \
    rm ${PODMAN_REMOTE_ARCHIVE}

VOLUME ["/home/jenkins/"]
USER jenkins